apiVersion: apps/v1 #与k8s集群版本有关，使用 kubectl api-versions 即可查看当前集群支持的版本
kind: Deployment #该配置的类型，我们使用的是 Deployment
metadata: #译名为元数据，即 Deployment 的一些基本属性和信息
  name: swag-deployment #Deployment 的名称
  labels: #标签，可以灵活定位一个或多个资源，其中key和value均可自定义，可以定义多组，目前不需要理解
    app: swag #为该Deployment设置key为app，value为nginx的标签
spec: #这是关于该Deployment的描述，可以理解为你期待该Deployment在k8s中如何使用
  replicas: 1 #使用该Deployment创建一个应用程序实例
  selector: #标签选择器，与上面的标签共同作用，目前不需要理解
    matchLabels: #选择包含标签app:nginx的资源
      app: swag
  template: #这是选择或创建的Pod的模板
    metadata: #Pod的元数据
      labels: #Pod的标签，上面的selector即选择包含标签app:nginx的Pod
        app: swag
    spec: #期望Pod实现的功能（即在pod中部署）
      containers: #生成container，与docker中的container是同一种
        - name: swag #container的名称
          image: linuxserver/letsencrypt #使用镜像nginx创建container，
          ports:
            - containerPort: 80 #内部服务暴露的端口
          resources:
            limits:
              memory: 512Mi
              cpu: "1"
            requests:
              memory: 256Mi
              cpu: "0.2"
---
apiVersion: v1
kind: Service #该配置的类型，我们使用的是 Service 服务类型
metadata:
  name: swag-service #该服务类型的名称
spec:
  selector: #选中的app部署实例
    app: swag #为该Deployment设置key为app，value为nginx的标签
  ports: #暴露的端口
    - protocol: TCP # 走得tcp 协议
      port: 80 #默认端口
      targetPort: 80 #内建服务端口
      nodePort: 30080 #对外服务端口
  type: NodePort
