{
 "title": "MediaSoup (default)",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Workers CPU",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    { "expr": "mediasoup_workers_cpu", "legendFormat": "CPU" },
    { "expr": "mediasoup_workers_count", "legendFormat": "Workers" }
   ]
  },
  {
   "title": "Workers Memory",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 0 },
   "yaxes": [
    { "format": "decmbytes" }
   ],
   "targets": [
    { "expr": "mediasoup_workers_memory / 1e6" }
   ]
  },
  {
   "title": "Tailchat meeting server CPU",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "rate(mediasoup_process_cpu_seconds_total[30s])",
     "legendFormat": "CPU"
    }
   ]
  },
  {
   "title": "Tailchat meeting server Memory",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 0 },
   "yaxes": [
    { "format": "decmbytes" }
   ],
   "targets": [
    {
     "expr": "mediasoup_process_resident_memory_bytes / 1e6"
    }
   ]
  },
  {
   "title": "Producers",
   "type": "graph",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "mediasoup_audio_in_count", "legendFormat": "Audio" },
    { "expr": "mediasoup_video_in_count", "legendFormat": "Video" }
   ]
  },
  {
   "title": "Input Bitrate",
   "type": "graph",
   "gridPos": { "h": 7, "w": 4, "x": 4, "y": 7 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "expr": "mediasoup_audio_bitrates_in_mean + mediasoup_video_bitrates_in_mean",
     "legendFormat": "Average"
    },
    {
     "expr": "mediasoup_audio_bitrates_in_min + mediasoup_video_bitrates_in_min",
     "legendFormat": "Min"
    },
    {
     "expr": "mediasoup_audio_bitrates_in_max + mediasoup_video_bitrates_in_max",
     "legendFormat": "Max"
    }
   ]
  },
  {
   "title": "Total Input Bitrate",
   "type": "graph",
   "gridPos": { "h": 7, "w": 4, "x": 8, "y": 7 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "expr": "mediasoup_audio_bitrates_in_sum",
     "legendFormat": "Audio"
    },
    {
     "expr": "mediasoup_video_bitrates_in_sum",
     "legendFormat": "Video"
    }
   ]
  },
  {
   "title": "Input packets",
   "type": "graph",
   "gridPos": { "h": 7, "w": 4, "x": 12, "y": 7 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "100 * mediasoup_packets_losts_in_sum / mediasoup_packets_counts_in_sum",
     "legendFormat": "Lost"
    },
    {
     "expr": "100 * mediasoup_packets_retransmitted_in_sum / mediasoup_packets_counts_in_sum",
     "legendFormat": "Retransmitted"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 7, "w": 3, "x": 16, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "mediasoup_rooms", "legendFormat": "Rooms" },
    { "expr": "mediasoup_peers", "legendFormat": "Peers" }
   ]
  },
  {
   "title": "Input scores",
   "type": "stat",
   "gridPos": { "h": 7, "w": 5, "x": 19, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "mediasoup_audio_scores_in_mean", "legendFormat": "Audio (average)" },
    { "expr": "mediasoup_audio_scores_in_min", "legendFormat": "Audio (min)" },
    { "expr": "mediasoup_audio_scores_in_max", "legendFormat": "Audio (max)" },
    { "expr": "mediasoup_video_scores_in_mean", "legendFormat": "Video (average)" },
    { "expr": "mediasoup_video_scores_in_min", "legendFormat": "Video (min)" },
    { "expr": "mediasoup_video_scores_in_max", "legendFormat": "Video (max)" }
   ]
  },
  {
   "title": "Consumers",
   "type": "graph",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "mediasoup_audio_out_count", "legendFormat": "Audio" },
    { "expr": "mediasoup_video_out_count", "legendFormat": "Video" }
   ]
  },
  {
   "title": "Output Bitrate",
   "type": "graph",
   "gridPos": { "h": 7, "w": 4, "x": 4, "y": 14 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "expr": "mediasoup_audio_bitrates_out_mean + mediasoup_video_bitrates_out_mean",
     "legendFormat": "Average"
    },
    {
     "expr": "mediasoup_audio_bitrates_out_min + mediasoup_video_bitrates_out_min",
     "legendFormat": "Min"
    },
    {
     "expr": "mediasoup_audio_bitrates_out_max + mediasoup_video_bitrates_out_max",
     "legendFormat": "Max"
    },
    {
     "expr": "mediasoup_audio_bitrates_out_p25 + mediasoup_video_bitrates_out_p25",
     "legendFormat": "25p"
    }
   ]
  },
  {
   "title": "Total Output Bitrate",
   "type": "graph",
   "gridPos": { "h": 7, "w": 4, "x": 8, "y": 14 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "expr": "mediasoup_audio_bitrates_out_sum",
     "legendFormat": "Audio"
    },
    {
     "expr": "mediasoup_video_bitrates_out_sum",
     "legendFormat": "Video"
    }
   ]
  },
  {
   "title": "Output RTT",
   "type": "graph",
   "gridPos": { "h": 7, "w": 4, "x": 12, "y": 14 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "mediasoup_round_trip_times_out_mean",
     "legendFormat": "Average"
    },
    {
     "expr": "mediasoup_round_trip_times_out_min",
     "legendFormat": "Min"
    },
    {
     "expr": "mediasoup_round_trip_times_out_max",
     "legendFormat": "Max"
    },
    {
     "expr": "mediasoup_round_trip_times_out_p25",
     "legendFormat": "25p"
    }
   ]
  },
  {
   "title": "Output Spatial Levels",
   "type": "graph",
   "gridPos": { "h": 7, "w": 4, "x": 16, "y": 14 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "mediasoup_spatial_layers_out_mean",
     "legendFormat": "Average"
    },
    {
     "expr": "mediasoup_spatial_layers_out_min",
     "legendFormat": "Min"
    },
    {
     "expr": "mediasoup_spatial_layers_out_max",
     "legendFormat": "Max"
    },
    {
     "expr": "mediasoup_spatial_layers_out_p25",
     "legendFormat": "25p"
    }
   ]
  },
  {
   "title": "Output Temporal Levels",
   "type": "graph",
   "gridPos": { "h": 7, "w": 4, "x": 20, "y": 14 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "mediasoup_temporal_layers_out_mean",
     "legendFormat": "Average"
    },
    {
     "expr": "mediasoup_temporal_layers_out_min",
     "legendFormat": "Min"
    },
    {
     "expr": "mediasoup_temporal_layers_out_max",
     "legendFormat": "Max"
    },
    {
     "expr": "mediasoup_temporal_layers_out_p25",
     "legendFormat": "25p"
    }
   ]
  }
 ]
}